version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/app/src
      - ./nodemon.json:/home/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
    depends_on:
      - redis
      - mongodb
  redis:
    image: "redis:6.2"
    ports:
      - "6380:6379"
  mongodb:
    image: "mongo:5.0"
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
